apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  project: my-project
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    path: manifest/
    repoURL: https://github.com/Manbqt/argocd-mbouquet.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
