username = ENV["USER"] || "mbraets"

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.synced_folder "shared/", "/vagrant_shared/"
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "#{username}S" do |server|
    server.vm.hostname = "#{username}S"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", privileged: true, path: "./scripts/server.sh", args: "192.168.56.110"
  end  

  config.vm.define "#{username}SW" do |serverWorker|
    serverWorker.vm.hostname = "#{username}SW"
    serverWorker.vm.network "private_network", ip: "192.168.56.111"

    serverWorker.vm.provision "shell", privileged: true, path: "./scripts/worker.sh", args: ["192.168.56.110", "6443"]
  end 

end
