Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.ssh.forward_agent = true

  config.vm.define "mbouquetS" do |server|
    server.vm.hostname = "mbouquetS"
    server.vm.network "private_network", ip: "192.168.56.110", hostname: true
  end  

  config.vm.define "mbouquetSW" do |serverWorker|
    serverWorker.vm.hostname = "mbouquetS"
    serverWorker.vm.network "private_network", ip: "192.168.56.111", hostname: true
  end 
  
  config.vm.provision "shell", inline: <<-SHELL
    echo "Hello Manon !"
  SHELL

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
