{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
spec:
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetport }}
  selector:
    app: {{ .name }}
---
{{- end }}
